version: v1.0
projects:
  - id: MyProject
    name: My Python Project
    buildType:
      - id: Build
        name: Build Python Project
        steps:
          - type: python
            name: Install Dependencies
            script:
              - pip install --upgrade pip
              - pip install telebot flask pymongo aiohttp psutil python-telegram-bot
          - type: command
            name: Make Executable
            script:
              - chmod +x *
              - chmod +x sharp
          - type: command
            name: Run Script
            script:
              - echo "Starting sharp.py..."
              - python sharp.py
